server:
  port: 8091
  servlet:
    context-path: /${application.name}

spring:
  application:
    name: ${application.name}
  profiles:
    active: ${environment}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}
        namespace: ${environment}

logging:
  charset:
    file: UTF-8
  file:
    name: log/pay.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 30
      file-name-pattern: log/pay.%d{yyyy-MM-dd}.%i.log